# Generated by Django 3.2 on 2020-09-20 03:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200920_0231'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_marketing_coordinator',
            field=models.BooleanField(default=False, verbose_name='marketing coordinator status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_marketing_manager',
            field=models.BooleanField(default=False, verbose_name='marketing manager status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
    ]
