# Generated by Django 3.2 on 2020-09-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200922_1603'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='faculty',
            table='Faculty',
        ),
    ]
