# Generated by Django 3.2 on 2020-09-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200927_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ctive',
            field=models.BooleanField(default=True),
        ),
    ]
