# Generated by Django 3.2 on 2020-09-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_is_ctive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_ctive',
        ),
    ]
