# Generated by Django 3.2 on 2020-09-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20200927_1122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='marketing_coordinator',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='marketing_manager',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_marketing_coordinator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_marketing_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='marketing_coordinator',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='marketing_manager',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_jobSeeker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('MC', 'Marketing Coordinator'), ('MM', 'Marketing Manager')], max_length=30, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
