# Generated by Django 3.2 on 2020-09-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200929_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('MC', 'Marketing Coordinator'), ('MM', 'Marketing Manager')], max_length=30, null=True, verbose_name='Role'),
        ),
    ]
