# Generated by Django 3.2 on 2020-10-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201001_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Student Number'),
        ),
    ]
