# Generated by Django 3.2 on 2020-10-06 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201002_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Mobile')),
                ('address', models.TextField(max_length=100, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guest',
                'db_table': 'Guest',
            },
            bases=('users.user',),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Student'), ('MC', 'Marketing Coordinator'), ('MM', 'Marketing Manager'), ('G', 'Guest')], max_length=30, null=True, verbose_name='Role'),
        ),
    ]
