# Generated by Django 3.2 on 2020-10-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20201006_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='faculty',
            field=models.OneToOneField(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.faculty', verbose_name='Faculty'),
        ),
    ]
