# Generated by Django 3.1.2 on 2020-10-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201025_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.AlterModelTable(
            name='admin',
            table='Admin User',
        ),
    ]
