# Generated by Django 3.1.2 on 2020-10-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0024_auto_20201025_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
