# Generated by Django 3.1.2 on 2020-10-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='academic_year',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('BM', 'Business Management'), ('MS', 'Medical Science'), ('ME', 'Mechantronic Engineering'), ('AF', 'Accounting and Financial')], max_length=50, null=True, unique=True, verbose_name='Academic Year'),
        ),
    ]
