# Generated by Django 3.1.2 on 2020-10-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20201025_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='academic_year',
            field=models.CharField(choices=[('1', '1st Academic Year'), ('2', '2nd Academic Year'), ('3', '3rd Academic Year'), ('4', '4th Academic Year'), ('5', '5th Academic Year')], max_length=50, null=True, unique=True, verbose_name='Academic Year'),
        ),
    ]
