# Generated by Django 3.1.2 on 2020-10-24 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20201023_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='academic_year',
            field=models.CharField(choices=[], max_length=50, null=True, verbose_name='Academic Year'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('name', 'academic_year')},
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Attendee', 'Attendee'), ('Customer', 'Customer'), ('Registrar', 'Registrar')], max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Customer'}, null=True, related_name='_academicyear_customers_+', to='users.AcademicYear')),
                ('employer', models.ForeignKey(blank=True, limit_choices_to={'role': 'Customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicyear')),
            ],
        ),
    ]
