# Generated by Django 3.1.2 on 2020-10-24 00:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20201024_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('Attendee', 'Attendee'), ('Customer', 'Customer'), ('Registrar', 'Registrar')], max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 10, 24, 0, 31, 53, 338897, tzinfo=utc))),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'Customer'}, null=True, related_name='_member_customers_+', to='users.Member')),
                ('employer', models.ForeignKey(blank=True, limit_choices_to={'role': 'Customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.member')),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
