# Generated by Django 3.1.2 on 2020-10-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20201024_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_closure_date', models.DateField(null=True, verbose_name='New Post Closure Date')),
                ('final_closure_date', models.DateField(null=True, verbose_name='Final Closure Date')),
                ('faculty', models.ManyToManyField(to='users.Faculty')),
            ],
        ),
    ]
