# Generated by Django 3.1.2 on 2020-10-24 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_academicyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='faculty',
        ),
        migrations.AddField(
            model_name='academicyear',
            name='academic_year',
            field=models.CharField(choices=[('1', 2015), ('2', 2016), ('3', 2017), ('4', 2018), ('5', 2019)], max_length=50, null=True, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicyear'),
        ),
    ]
