# Generated by Django 3.1.2 on 2020-10-24 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20201024_0742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Year'},
        ),
        migrations.AlterModelTable(
            name='academicyear',
            table='Academic Year',
        ),
    ]
