# Generated by Django 3.1.2 on 2020-10-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20201024_0749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='academic_year',
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
