# Generated by Django 3.1.2 on 2020-10-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20201024_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(choices=[('1', 2015), ('2', 2016), ('3', 2017), ('4', 2018), ('5', 2019)], max_length=50, null=True, verbose_name='Academic Year')),
                ('new_closure_date', models.DateField(null=True, verbose_name='New Post Closure Date')),
                ('final_closure_date', models.DateField(null=True, verbose_name='Final Closure Date')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Year',
                'db_table': 'Academic Year',
            },
        ),
    ]
