# Generated by Django 3.1.2 on 2020-10-24 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('name', 'academic_year')},
        ),
    ]
