# Generated by Django 3.1.2 on 2020-10-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20201024_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-academic_year'], 'verbose_name': 'Academic Year', 'verbose_name_plural': 'Academic Year'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['academic_year'], 'verbose_name': 'Faculty', 'verbose_name_plural': 'Faculties'},
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='final_closure_date',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='new_closure_date',
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='academic_year',
            field=models.CharField(choices=[('1', 2015), ('2', 2016), ('3', 2017), ('4', 2018), ('5', 2019)], max_length=50, null=True, unique=True, verbose_name='Academic Year'),
        ),
        migrations.CreateModel(
            name='FacultyAcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.academicyear')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.facultyacademicyear', verbose_name='Faculty'),
        ),
    ]
