# Generated by Django 3.1.2 on 2020-10-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20201029_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyacademicyear',
            options={'ordering': ['-academic_year'], 'verbose_name': 'Faculty Academic Year', 'verbose_name_plural': "Faculties' Academic Years"},
        ),
    ]
