# Generated by Django 3.2 on 2020-09-22 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0008_alter_faculty_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('date_posted', models.DateField(null=True, verbose_name='Date Posted')),
                ('time_posted', models.TimeField(auto_now=True, null=True, verbose_name='Time Posted')),
                ('paragraph1', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Paragraph-1')),
                ('image1', models.ImageField(upload_to='contributions', verbose_name='Image for Paragraph-1')),
                ('paragraph2', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Paragraph-2')),
                ('image2', models.ImageField(upload_to='contributions', verbose_name='Image for Paragraph-2')),
                ('paragraph3', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Paragraph-3')),
                ('image3', models.ImageField(upload_to='contributions', verbose_name='Image for Paragraph-3')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'db_table': 'Contributions',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
                ('date_posted', models.DateField(null=True, verbose_name='Date Posted')),
                ('time_posted', models.TimeField(auto_now=True, null=True, verbose_name='Time Posted')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.marketing_coordinator')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.contribution')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'Comments',
            },
        ),
    ]
