# Generated by Django 3.2 on 2020-09-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='date_posted',
            field=models.DateField(auto_now=True, null=True, verbose_name='Date Posted'),
        ),
    ]
