# Generated by Django 3.2 on 2020-09-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_alter_contribution_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='image1',
            field=models.ImageField(unique=True, upload_to='contributions', verbose_name='Image for Paragraph-1'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='image2',
            field=models.ImageField(unique=True, upload_to='contributions', verbose_name='Image for Paragraph-2'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='image3',
            field=models.ImageField(unique=True, upload_to='contributions', verbose_name='Image for Paragraph-3'),
        ),
    ]
