# Generated by Django 3.2 on 2020-09-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_auto_20200927_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='image1',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='contribution',
            old_name='paragraph3',
            new_name='paragraph',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='paragraph1',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='paragraph2',
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Selected'),
        ),
    ]
