# Generated by Django 3.2 on 2020-10-01 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201001_1252'),
        ('contributions', '0005_alter_contribution_paragraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Contribution', 'verbose_name_plural': 'Contributions'},
        ),
        migrations.AddField(
            model_name='contribution',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.faculty', verbose_name='Faculty'),
        ),
    ]
