# Generated by Django 3.2 on 2020-10-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_auto_20201001_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='contribution',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Paragraph1'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Paragraph2'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Paragraph3'),
        ),
    ]
