# Generated by Django 3.2 on 2020-10-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='time_posted',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='date_posted',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Posted'),
        ),
    ]
