# Generated by Django 3.2 on 2020-10-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_auto_20201002_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='images2',
            field=models.ImageField(null=True, upload_to='contributions', verbose_name='Image for Paragraph-2'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='images3',
            field=models.ImageField(null=True, upload_to='contributions', verbose_name='Image for Paragraph-3'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='images',
            field=models.ImageField(null=True, upload_to='contributions', verbose_name='Image for Paragraph-1'),
        ),
    ]
