# Generated by Django 3.2 on 2020-10-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0011_contribution_word_docu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Paragraph1'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='paragraph2',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Paragraph2'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='paragraph3',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Paragraph3'),
        ),
    ]
