# Generated by Django 3.2 on 2020-10-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0012_auto_20201006_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='paragraph2',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='paragraph3',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='title',
            field=models.CharField(default='No Title', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
