# Generated by Django 3.2 on 2020-10-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_auto_20201006_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='paragraph1',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='title',
        ),
    ]
