# Generated by Django 3.2 on 2020-10-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0014_auto_20201006_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='paragraph1',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Paragraph1'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='title',
            field=models.CharField(default='No Title', max_length=100, null=True, verbose_name='Title'),
        ),
    ]
