# Generated by Django 3.2 on 2020-10-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0015_auto_20201006_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='paragraph1',
        ),
        migrations.AddField(
            model_name='contribution',
            name='paragraphs',
            field=models.TextField(blank=True, max_length=15000, null=True, verbose_name='Paragraph1'),
        ),
    ]
