# Generated by Django 3.1.2 on 2020-10-29 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20201029_1039'),
        ('contributions', '0016_auto_20201006_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.facultyacademicyear', verbose_name='Faculty'),
        ),
    ]
